

const movieData = [
  {
    movieName: "Inception",
    movieDate: "2023-11-30",
    startTime: "15:00",
    endTime: "17:30",
    movieSeats:  [
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
    ],
  },
  {
    movieName: "The Matrix",
    movieDate: "2023-11-30",
    startTime: "18:00",
    endTime: "20:30",
    movieSeats:  [
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
    ],
  },
  {
    movieName: "The Dark Knight",
    movieDate: "2023-11-30",
    startTime: "21:00",
    endTime: "23:30",
    movieSeats:  [
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
    ],
  },
  {
    movieName: "Interstellar",
    movieDate: "2023-11-30",
    startTime: "14:30",
    endTime: "17:00",
    movieSeats:  [
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
    ],
  },
  {
    movieName: "Avatar",
    movieDate: "2023-11-30",
    startTime: "19:00",
    endTime: "21:30",
    movieSeats:  [
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
    ],
  },
  {
    movieName: "Titanic",
    movieDate: "2023-11-30",
    startTime: "20:00",
    endTime: "22:30",
    movieSeats:  [
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
    ],
  },
  {
    movieName: "Jurassic Park",
    movieDate: "2023-11-30",
    startTime: "17:30",
    endTime: "20:00",
    movieSeats:  [
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [true, true, true, true, true],
    ],
  },
];

export default movieData;
